name = "cork-board"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = ["/api/*"]

[[d1_databases]]
binding = "DB"
database_name = "corkboard"
database_id = "29f8f572-50e9-46f1-9338-1730d9b149b3"

[vars]
GOOGLE_CLIENT_ID = "REPLACE.apps.googleusercontent.com"
